--- 
assets: 
  self_host: 
    enabled: ~
    env: ~
avatar: /commons/avatar.jpg
baseurl: /dragonhunter69.github.io
collections: 
  tabs: 
    output: true
    sort_by: order
comments: 
  active: ~
  disqus: 
    shortname: ~
  giscus: 
    category: ~
    category_id: ~
    input_position: ~
    lang: ~
    mapping: ~
    reactions_enabled: ~
    repo: ~
    repo_id: ~
  utterances: 
    crossorigin: anonymous
    issue_term: pathname
    repo: airpark69/dragonhunter69.github.io
    theme: github-light
compress_html: 
  blanklines: false
  clippings: all
  comments: all
  endings: all
  ignore: 
    envs: 
      - development
  profile: false
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      comments: true
      layout: post
      permalink: "/posts/:title/"
      toc: true
  - 
    scope: 
      path: _drafts
    values: 
      comments: false
  - 
    scope: 
      path: ""
      type: tabs
    values: 
      layout: page
      permalink: "/:title/"
  - 
    scope: 
      path: assets/img/favicons
    values: 
      swcache: true
  - 
    scope: 
      path: assets/js/dist
    values: 
      swcache: true
description: "A minimal, responsive, and powerful Jekyll theme for presenting professional writing."
exclude: 
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json
github: 
  username: airpark69
google_analytics: 
  id: G-Z8L0EGT8F0
  pv: 
    cache_path: ~
    proxy_endpoint: ~
google_site_verification: ~
img_cdn: "https://raw.githubusercontent.com/cotes2020/chirpy-images/main"
jekyll-archives: 
  enabled: 
    - categories
    - tags
  layouts: 
    category: category
    tag: tag
  permalinks: 
    category: "/categories/:name/"
    tag: "/tags/:name/"
kramdown: 
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    block: 
      line_numbers: true
      start_line: 1
    css_class: highlight
    span: 
      line_numbers: false
lang: ko-KR
paginate: 10
prefer_datetime_locale: ~
pwa: 
  enabled: true
sass: 
  style: compressed
social: 
  email: example@doamin.com
  links: 
    - "https://twitter.com/username"
    - "https://github.com/username"
  name: DragonHunter69
tagline: "Losing is Fun"
theme: jekyll-theme-chirpy
theme_mode: light
timezone: Asia/Seoul
title: DragonHunter69
toc: true
twitter: 
  username: twitter_username
url: "https://airpark69.github.io/"